### ISSUE TITLE
2 Oct Codenight

### ISSUE THREAD

**Issue by iasoon** [ZeusWPI/MOZAIC#111]
Hi all!
Tonight we will make a last effort on our current ad-hoc setup, so that we can provide a nice and polished experience for the tournament that will take place right after our Zeus-quiz on 5 Oct.

Be sure to check out [our project board](https://github.com/ZeusWPI/MOZAIC/projects/5) to track progress!

Tonight's program:

# Server upgrade [Node.js]
We need some small improvements to our ad-hoc game server to host the tournament.
Infos: @wschella and @iasoon .

- [x] #110 Facilitate playing tournaments
- [x] #96 Improve bot pool

# THE GREAT REACT REWRITE [React, obviously]
The client and visualizer code is becoming unwieldy. We would like to port it to React in order to boost reusability and cleanliness.
Infos: @tl3ilaxu and @iasoon.

- [x] #90 port client
- [x] #109 port visualizer
- [x] #39 refactor the visualizer a bit to make it a properly reusable react component.

# Client improvements [Javascript]
Infos: @iasoon

- [ ] #94 try creating a rudimentary debugger
- [x] #103 Decent way to ask for user name
- [x] #101 Save&Load blockly bots

# Visualizer upgrade [Javascript]
Some added fanciness is always nice!
Infos: @tl3ilaxu 

- [ ] #32 Ship swarms in visualizer
- [ ] #43 Integrate @ajuvercr's voronoi diagram in the visualizer

**Comment by iasoon** [comment]
We got all the important ones down. Great job, guys!
And a special thanks to @wschella , @timodw , @myncke, @tl3ilaxu and @ajuvercr !
