### ISSUE TITLE
Codenight 15/11: Thermi Editie

### ISSUE THREAD

**Issue by wschella** [ZeusWPI/MOZAIC#128]
## Intro

The relevant branches are:
- [server/rust](https://github.com/ZeusWPI/MOZAIC), relevant files are in src/botdriver
- [client/js/electron](https://github.com/ZeusWPI/MOZAIC/tree/electron), relevant files are in src/games/planetwars/client, follow the README.md in that dir for setup

### Game server (local for now)
 - [ ] Lobby/Bot Pool/MatchMaker
 - [ ] MatchSetup/GameMatch
 - [ ] Filer/Executor
 - [ ] Ranker

### Gamerules
 - [ ] #114 Name shadowing

### Client  (Electron, TS)
 - [ ] #116 Create communication format utility
 - [ ] #132 Run botdriver from electron client
 - [ ]  #133 Create config form in client
 - [ ]  Gamelog visualisatie
 - [ ] More follows

### Visualizer (JS, D3)
 - [ ] #131 Port scoreboard to React
 - [ ] Unimportant tweaks: [Visualizer Upgrades](https://github.com/ZeusWPI/MOZAIC/milestone/3)

**Comment by iasoon** [comment]
Thanks for attending, everyone!
