### ISSUE TITLE
Packaging TODO's

### ISSUE THREAD

**Issue by wschella** [ZeusWPI/MOZAIC#177]
- [x] Move the data paths from the app directory the the OS default, see [this](https://codeburst.io/how-to-store-user-data-in-electron-3ba6bf66bc1e) (app.getPath)
- [x] Check binary handling (for gameserver)
- [x] Check visualizer resource handling
- [x] Preload some static assets
- [x] Add icons
- [x] Check build configuration and metadata
- [x] Auto updates
- [x] Add debug and console support

**Comment by wschella** [comment]
Closed in #183
