### ISSUE TITLE
Plan for coming days/weeks/month

### ISSUE THREAD

**Issue by wschella** [ZeusWPI/MOZAIC#23]
The most important components (visualizer/botdriver/gamerules) have a minimal working version or are close. This signals a time to get all of this shit together, reassess in what state we are in, and lay out our needs for the future.

Things that need to happen (somewhat in order)

 - [x]  Merge all (somewhat) finished branches and PR's. This includes @tl3ilaxu's visualizer things, @wschella's botdriver, @iasoon's gamerules, and bots by @timodw and @Str-Gen.
 - [x] Organize folders mainly per game, not per component. Includes JSON-Schema's, testbots, gamerules...
 - [x] Make things act nice together. Try to use a bot to play a game and visualize it. Clean out the kinks.
 - [x] Update documentation to reflect current state. Make it easy for coders to get things working.
 - [x] Decide how we want to go further with the project.
 - [x] Lay out new issue's and project boards to assist in giving an overview (for old and new coders) what can be improved.

**Comment by iasoon** [comment]
I feel a face-to-face discussion with the entire team would be productive, to assess our progress and align our outlooks. Introduction day is coming, and it feels quite feasible now to have our MVP demo there.

**Comment by wschella** [comment]
Point 1 and 2 are fixed since #27

**Comment by wschella** [comment]
We have a full implementation for HigherLower, and are close with the PlanetWars, I feel like we are in a state where we an write up the final issues and finish this MVP up.

**Comment by wschella** [comment]
Botdriver is finished, only issues remaining are integration issues, which will be written up soon, I see this as closed.
