### ISSUE TITLE
Introdag 2018

### ISSUE THREAD

**Issue by abeforgit** [ZeusWPI/MOZAIC#248]
A place to organize the work for the Introdag.

TODO:

- [ ] Blockly + visualizer webclient

- [ ] wrapper around the matchmaker to enable the webclient to interface with it

- [ ] server(s) configured to run the gameserver and matchmaker, preferably in VMs

- [ ] frontend for the matchmaker in the client?

Comment any questions, suggestions etc relating to the Introdag below.

**Comment by abeforgit** [comment]
I'll start: I assume we will be using the current release of the gameserver, and not the new event-driven one. Is this correct?

**Comment by iasoon** [comment]
I'd recommend using the new version, both to push the platform forwards and to familiarise everyone with the new system.

**Comment by abeforgit** [comment]
Ok in that case we need to make sure the matchmaker works with that version of the server.

@ajuvercr will this be a problem?
@wschella @Robbe7730  How bad does this destroy the hopes and dreams of the client?

**Comment by wschella** [comment]
I was under the impression that using the new version was the plan already, so not too much. Robbe started looking into porting the client already, but it had been a little difficult, so we might need to set up some minimum working examples outside of the client first. Getting the visualizer (and log viewer separated will be a good step for debugging things as well).

**Comment by Robbe7730** [comment]
I too tought we would use the new version. The porting of the client *shouldn't* be too hard, it just takes some time. I assume the matchmaker will be a lot more difficult, especially getting an interface for it in the client. It would also be nice (but not a necessity) to be able to play with the blockly users through the matchmaker.

**Comment by iasoon** [comment]
If we go for a real simple matchmaker (players connect, matchmaker waits until it has enough players, then starts a game), integrating it into everything shouldn't be too hard.

As for getting a web client to communicate with the MOZAIC system, I would either recommend either doing everything on the server, or everything on the client. In the latter scenario, you could use a websocket to send MOZAIC events to the server, which the server can then relay to the MOZAIC system using the client library.

**Comment by wschella** [comment]
I think i'm in favor of doing everything on the server. Feels easier.

**Comment by iasoon** [comment]
TODO:  review introdag and how we want to move further.
