### ISSUE TITLE
Intro day code sprint

### ISSUE THREAD

**Issue by iasoon** [ZeusWPI/MOZAIC#70]
Get our issue list all dressed up for our intro day code sprint!

All issues that
 - we NEED to finish: [here](https://github.com/ZeusWPI/MOZAIC/milestone/1).
 - we WANT to finish: [here](https://github.com/ZeusWPI/MOZAIC/milestone/2).
 - add up to Visualizer V2: [here](https://github.com/ZeusWPI/MOZAIC/milestone/3).

Tasks:
  - [x] curate issues for intro day
  - [x] clearer and prettier descriptions
  - [x] update some general docs
  - [x] very important: a new and shiny getting-started

**Comment by wschella** [comment]
I've updated this issue with links to relevant milestones. I made a distinction between things we actually need, and things we really want, but are not detrimental to a nice intro event.
